# Generated by Django 3.2.5 on 2022-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('lengra', 'LENGRA'), ('fojli', 'FOJLI'), ('himshangar', 'HIMSHAGAR'), ('aamruplai', 'AAMRUPALI')], default='Lengra', max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Pric_per_kg', models.IntegerField()),
            ],
        ),
    ]
