# Generated by Django 3.2.5 on 2022-05-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pric_per_kg',
            new_name='Price_per_kg',
        ),
    ]
