# Generated by Django 3.2.5 on 2022-05-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_pric_per_kg_product_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('lengra', 'LENGRA'), ('fojli', 'FOJLI'), ('himshangar', 'HIMSHAGAR'), ('aamruplai', 'AAMRUPALI'), ('khirshapat', 'KHIRSHAPAT'), ('gopalbhog', 'GOPALBHOG'), ('kalivog', 'KALIVOG'), ('mohonvog', 'MOHONVOG'), ('harivanga', 'HARIVANGA'), ('ashwina', 'ASHWINA')], default='Lengra', max_length=20),
        ),
    ]
