# Generated by Django 3.2.5 on 2022-05-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Img',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
