# Generated by Django 3.2.5 on 2022-05-14 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_total_quantity_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 15, 0, 51, 26, 999767)),
        ),
    ]
