# Generated by Django 3.2.5 on 2022-05-18 20:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 18, 20, 38, 40, 626613, tzinfo=utc)),
        ),
    ]
